/**
 * Emit the analytics contract.
 *
 * The same rhythm arithmetic exists twice: in TypeScript (`src/lib/analytics.ts`) for the
 * request path inside the app, and in Python (`services/insights/asteria_insights/`) for the
 * service that renders the atlas. Two implementations of one definition is a promise that
 * will be broken by a well-meaning edit, so the promise is written down instead:
 *
 *   contract/fixtures.json   a journal and a set of clocks to read it with
 *   contract/analytics.json  what TypeScript says about it
 *
 * `npm run test:unit` recomputes the second from the first and fails if it has drifted;
 * `npm run test:python` asserts Python produces the same bytes. The contract is therefore
 * checked from both sides, in both languages, on every run.
 *
 *   npx tsx scripts/emit-contract.ts           # write the files
 *   npx tsx scripts/emit-contract.ts --check    # fail if they are stale
 *
 * The fixtures are chosen for the places the two languages are most likely to disagree:
 * a spring-forward transition (where a local day is 23 hours long), a night at 23:55 that
 * belongs to the same local day as one two hours earlier, a moment that is "yesterday" at
 * the case's clock, an unparseable date, an unknown feeling, a brightness of zero, and
 * example moments that must be excluded by default.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { computeAnalytics, type MomentForAnalytics } from "../src/lib/analytics";

const ROOT = path.resolve(import.meta.dirname, "..");
const CONTRACT_DIR = path.join(ROOT, "contract");
const FIXTURES_PATH = path.join(CONTRACT_DIR, "fixtures.json");
const EXPECTED_PATH = path.join(CONTRACT_DIR, "analytics.json");

const moments: MomentForAnalytics[] = [
  // Three nights in a row in Toronto, through the spring-forward transition of 2026-03-08.
  { id: "a1", mood: "luminous", intensity: 4, createdAt: "2026-03-06T22:30:00.000Z", favorite: true },
  { id: "a2", mood: "tender", intensity: 3, createdAt: "2026-03-06T23:55:00.000Z" },
  { id: "a3", mood: "luminous", intensity: 5, createdAt: "2026-03-07T21:10:00.000Z" },
  { id: "a4", mood: "serene", intensity: 2, createdAt: "2026-03-08T03:30:00.000Z" },
  { id: "a5", mood: "electric", intensity: 1, createdAt: "2026-03-09T02:15:00.000Z" },
  { id: "a6", mood: "tender", intensity: 5, createdAt: "2026-03-10T01:05:00.000Z", favorite: true },
  { id: "a7", mood: "verdant", intensity: 3, createdAt: "2026-03-11T00:45:00.000Z" },
  // A twelve-night pause, then a night that is local *yesterday* relative to the clock below.
  { id: "a8", mood: "vesper", intensity: 4, createdAt: "2026-03-24T23:30:00.000Z" },
  { id: "a9", mood: "serene", intensity: 5, createdAt: "2026-03-25T02:00:00.000Z" },
  // Examples: present in every case, counted only when a case asks for them.
  { id: "e1", mood: "serene", intensity: 3, createdAt: "2026-02-01T12:00:00.000Z", isSample: true },
  { id: "e2", mood: "luminous", intensity: 2, createdAt: "2026-02-02T12:00:00.000Z", isSample: true },
  // Rows that must be dropped rather than guessed at.
  { id: "x1", mood: "wistful", intensity: 3, createdAt: "2026-03-07T12:00:00.000Z" },
  { id: "x2", mood: "serene", intensity: 3, createdAt: "not-a-date" },
  // A brightness outside 1–5: it counts as a moment, but it is not in the histogram or the mean.
  { id: "x3", mood: "tender", intensity: 0, createdAt: "2026-03-09T12:00:00.000Z" },
];

interface Case {
  id: string;
  timeZone: string;
  now: string;
  includeExamples: boolean;
  /** Read the journal as if nobody had written anything yet. */
  empty?: boolean;
}

const cases: Case[] = [
  { id: "toronto", timeZone: "America/Toronto", now: "2026-03-25T18:00:00.000Z", includeExamples: false },
  { id: "toronto-with-examples", timeZone: "America/Toronto", now: "2026-03-25T18:00:00.000Z", includeExamples: true },
  // 23:30 local: half of these moments fall on a different night than they do in Toronto.
  { id: "kolkata", timeZone: "Asia/Kolkata", now: "2026-03-25T18:00:00.000Z", includeExamples: false },
  // A clock just after midnight UTC, where "today" is a day the Toronto reading calls tomorrow.
  { id: "utc-midnight", timeZone: "UTC", now: "2026-03-25T00:30:00.000Z", includeExamples: false },
  { id: "nothing-yet", timeZone: "America/Toronto", now: "2026-03-25T18:00:00.000Z", includeExamples: false, empty: true },
];

const fixtures = {
  $comment:
    "Generated by scripts/emit-contract.ts. Read by tests/unit/analytics.contract.test.ts (TypeScript) and services/insights/tests/test_contract.py (Python).",
  moments,
  cases,
};

const expected = {
  version: 1,
  generatedBy: "scripts/emit-contract.ts",
  cases: cases.map(entry => ({
    id: entry.id,
    timeZone: entry.timeZone,
    now: entry.now,
    includeExamples: entry.includeExamples,
    expected: computeAnalytics(entry.empty ? [] : moments, {
      timeZone: entry.timeZone,
      now: new Date(entry.now),
      includeExamples: entry.includeExamples,
    }),
  })),
};

function write(file: string, value: unknown): void {
  mkdirSync(CONTRACT_DIR, { recursive: true });
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function stale(file: string, value: unknown): boolean {
  try {
    return readFileSync(file, "utf8") !== `${JSON.stringify(value, null, 2)}\n`;
  } catch {
    return true;
  }
}

if (process.argv.includes("--check")) {
  const drifted = [
    stale(FIXTURES_PATH, fixtures) ? "contract/fixtures.json" : null,
    stale(EXPECTED_PATH, expected) ? "contract/analytics.json" : null,
  ].filter(Boolean);
  if (drifted.length) {
    console.error(`✗ The analytics contract is out of date: ${drifted.join(", ")}`);
    console.error("  Run `npx tsx scripts/emit-contract.ts` and commit the result.");
    process.exit(1);
  }
  console.log("✓ Analytics contract is current.");
} else {
  write(FIXTURES_PATH, fixtures);
  write(EXPECTED_PATH, expected);
  console.log(`✓ Wrote contract/fixtures.json (${moments.length} moments, ${cases.length} cases)`);
  console.log("✓ Wrote contract/analytics.json");
}
