import { describe, expect, it } from "vitest";
import fixtures from "../../contract/fixtures.json" with { type: "json" };
import expected from "../../contract/analytics.json" with { type: "json" };
import { computeAnalytics, formatBps, formatScaled } from "@/lib/analytics";

/**
 * The TypeScript half of the analytics contract.
 *
 * `contract/analytics.json` is generated by `scripts/emit-contract.ts` from this very
 * implementation, which would make a naive golden-file test tautological. It is not
 * tautological here for two reasons: the file is *checked in*, so an edit to
 * `src/lib/analytics.ts` that changes a number fails this test until the contract is
 * regenerated and reviewed; and the same file is asserted by the Python tests, so the two
 * implementations are pinned to each other rather than to themselves.
 *
 * A failure here means one of three things, and the message says which: the arithmetic
 * changed, the contract is stale, or the contract file was edited by hand.
 */

const cases = expected.cases;

describe("analytics contract", () => {
  it("covers the cases that two implementations usually disagree about", () => {
    expect(cases.map(entry => entry.id)).toEqual([
      "toronto",
      "toronto-with-examples",
      "kolkata",
      "utc-midnight",
      "nothing-yet",
    ]);
    // A spring-forward night, a 23:55 moment, a brightness of zero, an unparseable date,
    // an unknown feeling, and example moments that must be excluded by default.
    expect(fixtures.moments.length).toBeGreaterThan(10);
  });

  for (const entry of cases) {
    it(`reproduces the checked-in reading for ${entry.id}`, () => {
      const moments = entry.id.startsWith("nothing") ? [] : fixtures.moments;
      const produced = computeAnalytics(moments, {
        timeZone: entry.timeZone,
        now: new Date(entry.now),
        includeExamples: entry.includeExamples,
      });
      expect(produced).toEqual(entry.expected);
    });
  }

  it("keeps the fixture journal meaningful", () => {
    const toronto = cases.find(entry => entry.id === "toronto")!.expected;
    const withExamples = cases.find(entry => entry.id === "toronto-with-examples")!.expected;
    const kolkata = cases.find(entry => entry.id === "kolkata")!.expected;

    expect(toronto.totals.moments).toBe(10);
    expect(toronto.totals.examples).toBe(2);
    expect(withExamples.totals.moments).toBe(12);
    expect(toronto.cadence.longestRun).toBe(5);
    expect(toronto.cadence.longestGapDays).toBe(14);
    expect(toronto.intensity.histogram[0]).toBe(0);
    expect(kolkata.hours).not.toEqual(toronto.hours);
    // Every ratio is an integer, which is the whole reason the two languages can be
    // compared by equality at all.
    for (const mood of toronto.moods) {
      expect(Number.isInteger(mood.shareBps)).toBe(true);
      expect(Number.isInteger(mood.avgIntensityX100)).toBe(true);
    }
  });

  it("never sees the writing", () => {
    // The analytics input is metadata only: no title, no body. If this ever changes, the
    // service in `services/insights` starts receiving a journal's words and the privacy
    // claim in the README becomes false.
    const allowed = new Set(["id", "mood", "intensity", "createdAt", "favorite", "isSample"]);
    for (const moment of fixtures.moments) {
      for (const key of Object.keys(moment)) expect(allowed.has(key)).toBe(true);
    }
  });
});

describe("formatting the integers back for display", () => {
  it("renders basis points the way a writer reads them", () => {
    expect(formatBps(0)).toBe("0%");
    expect(formatBps(2000)).toBe("20%");
    expect(formatBps(1234)).toBe("12.34%");
  });

  it("renders a scaled average", () => {
    expect(formatScaled(320, 100)).toBe("3.2");
    expect(formatScaled(0, 100)).toBe("0.0");
    expect(formatScaled(255, 100, 2)).toBe("2.55");
  });
});
